# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: ibus-table
email: "Mike FABIAN <mfabian@redhat.com>, Caius CHANCE <kaio@fedoraproject.org>"
description: > # this means to ignore newlines until "baseurl:"
    IBus-Table is the IM Engine framework for table-based input methods, 
    mostly Chinese input methods such as ZhengMa, WuBi, ErBi, CangJie.
baseurl: "/ibus-table" # the subpath of your site, e.g. /blog
url: "https://mike-fabian.github.io" # the base hostname & protocol for your site
github_username:  mike-fabian

# Build settings
markdown: kramdown
